services:
  - type: static
    name: health-stats-frontend
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://health-stats-api.onrender.com
      - key: VITE_API_TIMEOUT
        value: "30000"
      - key: VITE_ENABLE_MOCK_DATA
        value: "false"
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-store
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
